[tool.poetry]
name = "eng-dados"
version = "0.1.0"
description = ""
authors = ["Guilherme Prado <gui_prado@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
